version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: recipe_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: # enter password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: recipe_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: recipe_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic_kibana_network
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: recipe_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic_kibana_network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
  elasticsearch_data:

networks:
  elastic_kibana_network:
    name: elastic_kibana_network

# this is used to spin up the required mongodb and redis containers
# MongoDB is used as the primary database
# Redis is used as the cache